# Para executar basta digitar no console make (enter) e depois ./exec (enter)
exec: main.c BMH.c ForcaBruta.c LeituraArquivo.c ShiftAndAproximado.c
	gcc -o exec main.c BMH.c ForcaBruta.c LeituraArquivo.c ShiftAndAproximado.c

clean:
	rm exec 
